- name: Setup Gateway Server
  hosts: gateway
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy gateway Dockerfile
      copy:
        src: ../../gateway/Dockerfile
        dest: /opt/gateway/

    - name: Copy gateway files
      copy:
        src: ../../gateway/
        dest: /opt/gateway/gateway/

    - name: Copy requirements
      copy:
        src: ../../requirements.txt
        dest: /opt/gateway/

    - name: Build gateway image
      docker_image:
        name: kv-gateway
        build:
          path: /opt/gateway
        source: build

    - name: Set backend servers variable
      set_fact:
        backend_servers_list: "{{ groups['servers'] | map('extract', hostvars, 'ansible_host') | list }}"

    - name: Build backend servers string
      set_fact:
        backend_servers_string: "{{ backend_servers_list | map('regex_replace', '^(.*)$', '\\1:8080') | join(',') }}"

    - name: Final backend servers string
      debug:
        msg: "Final BACKEND_SERVERS will be: {{ backend_servers_string }}"

    - name: Stop existing gateway container
      docker_container:
        name: kv-gateway
        state: absent
      ignore_errors: yes

    - name: Remove any containers using port 8000
      shell: docker ps -a --filter "publish=8000" -q | xargs -r docker rm -f
      ignore_errors: yes

    - name: Kill any process using port 8000
      shell: lsof -ti:8000 | xargs -r kill -9
      ignore_errors: yes

    - name: Wait for port to be released
      wait_for:
        port: 8000
        state: stopped
        timeout: 10
      ignore_errors: yes

    - name: Run gateway container
      docker_container:
        name: kv-gateway
        image: kv-gateway
        ports:
          - "8000:8000"
        env:
          BACKEND_SERVERS: "{{ backend_servers_string }}"
        restart_policy: unless-stopped

- name: Setup Backend Servers
  hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy server Dockerfile
      copy:
        src: ../../server/Dockerfile
        dest: /opt/server/

    - name: Copy server files
      copy:
        src: ../../server/
        dest: /opt/server/server/

    - name: Copy requirements
      copy:
        src: ../../requirements.txt
        dest: /opt/server/

    - name: Copy base database file
      copy:
        src: ../../data/kv_store.db
        dest: /opt/server/base-kv_store.db
      ignore_errors: yes

    - name: Create Docker volume for server data
      docker_volume:
        name: "kv-server-{{ inventory_hostname }}-data"
        driver: local

    - name: Initialize database in volume
      shell: |
        docker run --rm \
          -v kv-server-{{ inventory_hostname }}-data:/data \
          -v /opt/server/base-kv_store.db:/base-kv_store.db \
          alpine:latest sh -c "
            if [ ! -f /data/kv_store.db ]; then
              if [ -f /base-kv_store.db ]; then
                cp /base-kv_store.db /data/kv_store.db
                echo 'Copied base database for {{ inventory_hostname }}'
              else
                touch /data/kv_store.db
                echo 'Created empty database for {{ inventory_hostname }}'
              fi
            else
              echo 'Database already exists for {{ inventory_hostname }}'
            fi
          "
      ignore_errors: yes

    - name: Build server image
      docker_image:
        name: kv-server
        build:
          path: /opt/server
        source: build

    - name: Stop existing server container
      docker_container:
        name: "kv-server-{{ inventory_hostname }}"
        state: absent
      ignore_errors: yes

    - name: Remove any containers using port 8080
      shell: docker ps -a --filter "publish=8080" -q | xargs -r docker rm -f
      ignore_errors: yes

    - name: Kill any process using port 8080
      shell: lsof -ti:8080 | xargs -r kill -9
      ignore_errors: yes

    - name: Wait for port 8080 to be released
      wait_for:
        port: 8080
        state: stopped
        timeout: 10
      ignore_errors: yes

    - name: Run server container
      docker_container:
        name: "kv-server-{{ inventory_hostname }}"
        image: kv-server
        ports:
          - "8080:8080"
        volumes:
          - "kv-server-{{ inventory_hostname }}-data:/app/data"
        restart_policy: unless-stopped
    
    - name: Install UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Block external access to server port
      ufw:
        rule: deny
        port: '8080'
        src: '0.0.0.0/0'
        
    - name: Allow gateway access to servers
      ufw:
        rule: allow
        port: '8080'
        src: "{{ hostvars[groups['gateway'][0]]['ansible_host'] }}"