---
# Simple Ansible playbook for Key-Value Store deployment
# Usage: ansible-playbook -i hosts.yaml playbook.yaml

- name: Install Docker on all servers
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Deploy API Gateway
  hosts: gateway
  become: yes
  tasks:
    - name: Copy application files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /opt/kv-store
        mode: '0644'

    - name: Create gateway docker-compose file
      copy:
        content: |
          version: '3.8'
          services:
            api-gateway:
              build:
                context: .
                dockerfile: gateway/Dockerfile
              ports:
                - "8000:8000"
              restart: unless-stopped
              environment:
                - PYTHONUNBUFFERED=1
        dest: /opt/kv-store/docker-compose.yml
        mode: '0644'

    - name: Start API Gateway
      docker_compose:
        project_src: /opt/kv-store
        build: yes
        state: present

- name: Deploy Backend Servers
  hosts: servers
  become: yes
  tasks:
    - name: Copy application files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /opt/kv-store
        mode: '0644'

    - name: Create data directory
      file:
        path: /opt/kv-store/data
        state: directory
        mode: '0755'

    - name: Create server docker-compose file
      copy:
        content: |
          version: '3.8'
          services:
            kv-store-server:
              build:
                context: .
                dockerfile: server/Dockerfile
              ports:
                - "8080:8080"
              volumes:
                - ./data:/app/data
              restart: unless-stopped
              environment:
                - PYTHONUNBUFFERED=1
        dest: /opt/kv-store/docker-compose.yml
        mode: '0644'

    - name: Start Backend Server
      docker_compose:
        project_src: /opt/kv-store
        build: yes
        state: present

- name: Update Gateway Configuration
  hosts: gateway
  become: yes
  tasks:
    - name: Update gateway to route to backend servers
      replace:
        path: /opt/kv-store/gateway/main.py
        regexp: 'BACKEND_URL = "http://server-1:8080"'
        replace: |
          BACKEND_URL = "http://{{ hostvars[groups['servers'][0]]['ansible_host'] }}:8080"
